### ISSUE TITLE
RadarrLookup by IMDBID

### ISSUE THREAD

**Issue by Fyb3roptik** [golift/starr#106]
I need to be able to use the /lookup/imdb endpoint. Any chance at getting that? Thanks

**Comment by davidnewhall** [comment]
Looks like an easy one. I'm knee deep in other projects, but can get to it eventually. If you want to submit a PR we'll get there quicker.

**Comment by davidnewhall** [comment]
Just verifying this is for Radarr only? I don't see the same endpoint on Sonarr.

**Comment by Fyb3roptik** [comment]
Right this ia for Radarr only

**Comment by davidnewhall** [comment]
Can you test the linked PR?
