### ISSUE TITLE
Radarr Telegram Bot

### ISSUE THREAD

**Issue by woiza** [golift/starr#135]
Hi,

I am not sure if is worth mentioning on your page, but I wrote a small Radarr Telegram bot using your library:
https://github.com/woiza/telegram-bot-radarr
Thanks a lot for your library! It made development much easier and faster compared to using Radarr's openapi spec.

**Comment by austinwbest** [comment]
I dont use telegram but looks good! Some thoughts of what will come up

- Picking an instance for those who use multiple
- Picking a profile
- Picking movie only or collection
- Assigning tags for requested movies (general tags, user tags, etc)
- Search after add option
- Approval for requests if more than just one user

I know this isnt really the place for a full on conversation but figured i would give you some things to think about :)

**Comment by woiza** [comment]
Thanks!
- Picking a profile and a root folder is already implemented (if you have only one, then it is picked automatically without asking for it)
- More than one user is supported by providing a list of Telegram user IDs


I will start working on the other features in January.

What do you mean with "Search after add option"? Could you give an example?

**Comment by davidnewhall** [comment]
`Search after add option` is a feature of the starr app I believe. When you add new content, you check a box to search for things right now.

**Comment by woiza** [comment]
Thanks, I figured it out and this option can be chosen in the last step when adding a new movie.
