### ISSUE TITLE
Support the Parse endpoint

### ISSUE THREAD

**Issue by madmatt** [golift/starr#145]
Sonarr has a `/api/v3/parse` endpoint that takes a generic text string `Title` and can parse it and return series/episode data. Very useful to convert a filename into structured data.

Context: I'm creating a script that will automatically watch a folder for IO changes, run `Parse` on any files added, and if it detects a series/episode, automatically issue a `ManualImportReprocess` command with the filename and the details from the `Parse` (e.g. which series and episode ID it should be processed against).

I'm not sure if I'm going about this the right way or not - essentially I am trying to create a way to automatically import files from a source that isn't supported by Sonarr (think an Emby instance or some other fileshare service that Sonarr doesn't integrate with directly).

Thanks!

**Comment by davidnewhall** [comment]
I don't see a problem with adding a parse method to sonarr.

> I'm creating a script

You mean a go app? 

> I'm not sure if I'm going about this the right way or not

Not real sure either, you might consider asking in the #sonarr or #3rd-party channel on Servarr discord.

**Comment by madmatt** [comment]
Sorry, yes a Go app. Good idea on where to ask, I'll check in over there. Thanks!

**Comment by davidnewhall** [comment]
Still need the code? I committed it. Can you test it?

**Comment by madmatt** [comment]
Amazing, thank you for this! I'll test it out when I get some time, sorry for the delay!
