### ISSUE TITLE
Sonarr monitoring options

### ISSUE THREAD

**Issue by maximator100** [golift/starr#146]
I am struggling with monitoring options:

![monitor](https://github.com/golift/starr/assets/155834830/44ba3105-9e4c-4830-9f9c-2db103cb0870)

Did you miss something?

Sonarr api docs:
```  
"addOptions": {
    "ignoreEpisodesWithFiles": true,
    "ignoreEpisodesWithoutFiles": true,
    "monitor": "unknown",
    "searchForMissingEpisodes": true,
    "searchForCutoffUnmetEpisodes": true
  },
```
  
starr:
 ```
type AddSeriesOptions struct {
	SearchForMissingEpisodes     bool `json:"searchForMissingEpisodes"`
	SearchForCutoffUnmetEpisodes bool `json:"searchForCutoffUnmetEpisodes,omitempty"`
	IgnoreEpisodesWithFiles      bool `json:"ignoreEpisodesWithFiles,omitempty"`
	IgnoreEpisodesWithoutFiles   bool `json:"ignoreEpisodesWithoutFiles,omitempty"`
}
```

Sonarr version 4.0.2.1183

**Comment by davidnewhall** [comment]
Hello,

Seems like it's missing. Does it work if you add it?

**Comment by maximator100** [comment]
Yes, it does.

Monitor future episodes:
![future](https://github.com/golift/starr/assets/155834830/0fee5d85-8b1c-4e6c-8be2-7f02709a03f2)

Monitor first season:
![firstSeason](https://github.com/golift/starr/assets/155834830/67884c68-121a-4e33-940d-c816e90d1e4b)
