### ISSUE TITLE
radarr /movie/lookup

### ISSUE THREAD

**Issue by smantic** [golift/starr#15]
https://radarr.video/docs/api/#/Movie/get-movie-lookup

I actually have my own implementation [here](https://github.com/smantic/plexer/blob/e161b98d0b878c8b3c72444a8351bf28faf24b83/pkg/radarr/movies.go#L103). But I've since found this library and would like to use it instead of implementing everything from scratch.

**Comment by austinwbest** [comment]
This endpoint in all of them would actually be useful. I could make use of them as well and offload some api hits back to their client so if you add them all, expose them with endpoints for notifiarr 😍

**Comment by smantic** [comment]
@austinwbest Im not familar with all of the *arr APIs, so I'll add others as I read their docs. 
 I have no idea what exposing endpoints for notifarr would entail.

**Comment by austinwbest** [comment]
> @austinwbest Im not familar with all of the *arr APIs, so I'll add others as I read their docs. 
>  I have no idea what exposing endpoints for notifarr would entail.

It was more a note for David :)

So the arr apps use the same api, difference being the semantics for its type. albumId, authorId, movieId, seriesId, etc

**Comment by davidnewhall** [comment]
This is probably easy to implement in the rest of the apps. I left a review on your pull request. If this does indeed re-use the `Movie` type then it may be a drop-in for the other apps as well. I'll make sure this issue stays open until we get them all. Thanks for your contribution!

**Comment by davidnewhall** [comment]
i'll test the new lookup function and try to add the other 3 in the next week or so. then I'll cut a new release.
