### ISSUE TITLE
Bazarr and Jackett

### ISSUE THREAD

**Issue by creptt** [golift/starr#2]
I am actually working on a project, when I ran into your library for Sonarr and Radarr which I need; however, another library that would go hand in hand with your collection would be Bazarr (A subtitle framework) and Jackett (a torrent indexer framework) which go hand in hand with your current collection of Go-SDK's. Unfortunately I don't have the skills or knowledge to do so myself.  Please tell me your thoughts or how I can help.

Thanks,
Napoleon
nbchasingit247@gmail.com

**Comment by davidnewhall** [comment]
Not a bad idea, but just to be clear, those would be "other libraries" and not a part of _this_ library. It's difficult enough to maintain all four starr apps in this library without adding apps that have entirely different APIs.

If you're writing a go app to interface with an API, then you certainly have the skills and knowledge to write a library that does the same thing. I've written API libraries for a number of apps, and I can give you pointers if you'd like. Drop by my Discord.

All that said, I like the idea, but I've never had to interact with those application APIs myself and I'm not looking for another package to maintain. If you want help, I'm OK with that, but I'd rather not write that code from scratch. I'm also quite willing to let you host it on golift.io and give you a `golift/repo` if you're interested. 

To get started, figure out how to login to those applications. Jackett is probably as easy as pass the api key in a header, but I haven't a clue what bazarr does off hand.  Once you have that working, you want to start making requests to the API and getting the payloads. I use this tool religiously to convert JSON (from APIs) to Go structs: https://mholt.github.io/json-to-go/ - it's not perfect and you will often need to tweak some stuff, but it does a fine job at the base structure.

The code in the _starr_ library, in http.go, interface.go and starr.go files, is decent boilerplate to get started. You can damn near copy those files and just rename starr to jackett, etc, and start building out a library. You then add methods and types for each api path.

Good luck!
-david

**Comment by davidnewhall** [comment]
I also recently re-wrote this library to add many more methods for every app. It used to be much smaller. You can see the "smaller" version here: https://github.com/golift/starr/tree/v0.9.4 - that may be easier to comprehend.

**Comment by davidnewhall** [comment]
Looking at this library more, it may actually be "not that hard" to add other applications as sub packages like I did with the starr apps.

**Comment by davidnewhall** [comment]
Can you give me more idea what methods/data you want from these apps? I'v only added about 10% of the starr app methods: the ones folks need. Let me know what you need, and if you know the API paths. I can look into adding this.

**Comment by davidnewhall** [comment]
Hello? .....
