### ISSUE TITLE
Add episodefile API for Sonarr

### ISSUE THREAD

**Issue by Rich7690** [golift/starr#28]
Hey any chance you might implement https://github.com/Sonarr/Sonarr/wiki/EpisodeFile ?

**Comment by davidnewhall** [comment]
Sure.

**Comment by davidnewhall** [comment]
Please test the linked pull request at your convenience. 
```
go get golift.io/starr@6e4e80bb96fd823368ca14696a3c4d99e7adeaf9
```

**Comment by Rich7690** [comment]
> Please test the linked pull request at your convenience.
> 
> ```
> go get golift.io/starr@6e4e80bb96fd823368ca14696a3c4d99e7adeaf9
> ```

Will do shortly. Thanks for the quick turn around :D

**Comment by Rich7690** [comment]
Just tested it. Looks good to me. 👍
