### ISSUE TITLE
Add lidarr trackfile endpoints

### ISSUE THREAD

**Issue by aetaric** [golift/starr#55]
Calling lidarr works great and all... but currently working with the files is a bit, scuffed. The trackfile endpoints would help there. 

https://lidarr.audio/docs/api/#/TrackFile

**Comment by davidnewhall** [comment]
This shouldn't be too difficult. Curious.. The spec shows `audioTags` as a json key. Do you ever get that key? I don't.

**Comment by davidnewhall** [comment]
@aetaric Have a chance to test those changes yet?

**Comment by davidnewhall** [comment]
Just re-open or open a new issue if this has any problems. I got you.
