### ISSUE TITLE
Update System/Status to pull all fields in api

### ISSUE THREAD

**Issue by bakerboy448** [golift/starr#67]
- [x] [Radarr](https://github.com/Radarr/Radarr/blob/develop/src/Radarr.Api.V3/System/SystemController.cs)
- [x] [Sonarr](https://github.com/Sonarr/Sonarr/blob/develop/src/Sonarr.Api.V3/System/SystemController.cs)
- [x] [Lidarr](https://github.com/Lidarr/Lidarr/blob/develop/src/Lidarr.Api.V1/System/SystemController.cs)
- [x] [Readarr](https://github.com/Readarr/Readarr/blob/develop/src/Readarr.Api.V1/System/SystemController.cs)
- [x] [Prowlarr](https://github.com/Prowlarr/Prowlarr/blob/develop/src/Prowlarr.Api.V1/System/SystemController.cs)

**Comment by davidnewhall** [comment]
now go into your notifiarr debug log, search for "system/status" and attach the json payloads for each. :)
